[pytest]
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
markers =
    module_under_test: hvilket modul nicegui.testing skal bygge siden fra
filterwarnings =
    ignore::DeprecationWarning
